theme = "catppuccin_mocha"

[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
"minus" = ["file_picker_in_current_directory"]
X = ["extend_line_up", "extend_to_line_bounds"]

[editor]
cursorline = true
color-modes = true
auto-save = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]

[editor.soft-wrap]
enable = true