theme = "onedark"

[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
g = { a = "code_action" }
esc = ["collapse_selection", "keep_primary_selection"]

[editor]
cursorline = true
color-modes = true
auto-save = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true