theme = "catppuccin_mocha"

[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
"minus" = ["file_picker_in_current_directory"]
X = ["extend_line_up", "extend_to_line_bounds"]
"tab" = ["jump_forward"]
"%" = ["save_selection", "select_all"]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"

[editor]
lsp.enable = false
cursorline = true
auto-save = true
bufferline = "always"
auto-pairs = false
idle-timeout = 200
color-modes = true
mouse = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"
