[[language]]
name = "python"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "gradlew"]
language-server = { command = "jdtls" }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "vue"
scope = "source.vue"
injection-regex = "vue"
file-types = ["vue"]
roots = ["package.json", "vue.config.js"]
indent = { tab-width = 2, unit = "  " }
language-server = { command = "vls --stdio" }
