[[language]]
name = "python"
auto-format = true

[[language]]
name = "java"
auto-format = true
file-types = ["java", "groovy", "Jenkinsfile", "jenkinsfile"]

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
