[".zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"

[".zsh/zsh-history-substring-search"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search.git"
    refreshPeriod = "168h"

[".zsh/pure"]
    type = "git-repo"
    url = "https://github.com/sindresorhus/pure.git"
    refreshPeriod = "168h"

[".zsh/fast-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    refreshPeriod = "168h"

[".zsh/zsh-private-config"]
    type = "git-repo"
    url = "git@github.com:eckelon/zsh-private-config.git"
    refreshPeriod = "168h"

[".claude/skills"]
    type = "git-repo"
    url = "git@github.com:eckelon/skills.git"
    refreshPeriod = "168h"

[".emacs.d/emacs-solo"]
    type = "git-repo"
    url = "https://github.com/LionyxML/emacs-solo.git"
    refreshPeriod = "168h"
