[character]
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'
[nodejs]
disabled = true
[docker_context]
disabled = true
[package]
disabled = true
[python]
detect_files = ['Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']
