#!/bin/bash
# Applies Superkey preferences and restarts the app if running.
# Auto-generated by scripts/capture-superkey-settings.sh — do not edit.

defaults write com.knollsoft.Superkey KeyboardShortcuts_toggleSeek -string '{"carbonModifiers":6912,"carbonKeyCode":1}'
defaults write com.knollsoft.Superkey SUEnableAutomaticChecks -int 0
defaults write com.knollsoft.Superkey capsHjklArrows -int 1
defaults write com.knollsoft.Superkey capsLockKeycode -int -1
defaults write com.knollsoft.Superkey capsLockRemapped -int 1
defaults write com.knollsoft.Superkey executeQuickHyperKey -int 1
defaults write com.knollsoft.Superkey hideMenuBarIcon -int 1
defaults write com.knollsoft.Superkey hyperDeleteToForward -int 1
defaults write com.knollsoft.Superkey hyperFlags -int 1966080
defaults write com.knollsoft.Superkey keyRemap -int 1
defaults write com.knollsoft.Superkey launchOnLogin -int 1
defaults write com.knollsoft.Superkey minAxCharCount -int 2
defaults write com.knollsoft.Superkey physicalKeycode -int 231
defaults write com.knollsoft.Superkey quickHyperKeycode -int 53
defaults write com.knollsoft.Superkey quickPressTimeout -float 0.6505003
defaults write com.knollsoft.Superkey seekOptions -int 3

if pgrep -qx Superkey; then
  killall Superkey
  sleep 1
  open -a Superkey
fi
