#!/bin/bash
# Captures current Superkey plist settings and regenerates:
#   1. ~/.config/superkey/apply-defaults.sh  (shared apply script)
#   2. chezmoi run_onchange script            (calls the shared script)
#   3. LaunchAgent plist                      (reboot protection)
#
# Usage: ./scripts/capture-superkey-settings.sh

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
apply_script="$repo_root/home/dot_config/superkey/executable_apply-defaults.sh"
onchange="$repo_root/home/run_onchange_after_apply-superkey-settings.sh.tmpl"
launchagent_dir="$repo_root/home/Library/LaunchAgents"
launchagent="$launchagent_dir/com.user.superkey-settings.plist"

keys=(
  KeyboardShortcuts_toggleSeek
  SUEnableAutomaticChecks
  capsHjklArrows
  capsLockKeycode
  capsLockRemapped
  executeQuickHyperKey
  hideMenuBarIcon
  hyperDeleteToForward
  hyperFlags
  keyRemap
  launchOnLogin
  minAxCharCount
  physicalKeycode
  quickHyperKeycode
  quickPressTimeout
  seekOptions
)

defaults_cmds=()

for key in "${keys[@]}"; do
  val=$(defaults read com.knollsoft.Superkey "$key" 2>/dev/null || true)
  if [ -z "$val" ]; then
    echo "⚠  Skipping $key (not found in defaults)"
    continue
  fi
  if [[ "$val" =~ ^-?[0-9]+$ ]]; then
    defaults_cmds+=("defaults write com.knollsoft.Superkey $key -int $val")
  elif [[ "$val" =~ ^-?[0-9]*\.[0-9]+$ ]]; then
    defaults_cmds+=("defaults write com.knollsoft.Superkey $key -float $val")
  else
    defaults_cmds+=("defaults write com.knollsoft.Superkey $key -string '$val'")
  fi
done

# --- 1. Generate shared apply script ---
{
  cat << 'HEADER'
#!/bin/bash
# Applies Superkey preferences and restarts the app if running.
# Auto-generated by scripts/capture-superkey-settings.sh — do not edit.

HEADER
  printf '%s\n' "${defaults_cmds[@]}"
  cat << 'FOOTER'

if pgrep -qx Superkey; then
  killall Superkey
  sleep 1
  open -a Superkey
fi
FOOTER
} > "$apply_script"
echo "✓ Generated $apply_script"

# --- 2. Generate chezmoi run_onchange script ---
{
  cat << 'HEADER'
#!/bin/bash
# Delegates to the shared apply script.
# Run via chezmoi on change — auto-generated by capture-superkey-settings.sh
#
HEADER
  printf '# %s\n' "${defaults_cmds[@]}"
  echo ""
  echo 'exec "$HOME/.config/superkey/apply-defaults.sh"'
} > "$onchange"
chmod +x "$onchange"
echo "✓ Generated $onchange"

# --- 3. Generate LaunchAgent ---
mkdir -p "$launchagent_dir"
cat > "$launchagent" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.user.superkey-settings</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>sleep 8; exec "$HOME/.config/superkey/apply-defaults.sh"</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
EOF
echo "✓ Generated $launchagent"
