#!/bin/bash
# Captures current Superkey plist settings and regenerates the run_onchange script
# Run after changing Superkey preferences
#
# Usage: ./scripts/capture-superkey-settings.sh

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
target="$repo_root/home/run_onchange_after_apply-superkey-settings.sh.tmpl"

keys=(
  KeyboardShortcuts_toggleSeek
  SUEnableAutomaticChecks
  capsHjklArrows
  capsLockKeycode
  capsLockRemapped
  executeQuickHyperKey
  hyperDeleteToForward
  hyperFlags
  keyRemap
  launchOnLogin
  minAxCharCount
  physicalKeycode
  quickHyperKeycode
  seekOptions
)

cat > "$target" << 'HEADER'
#!/bin/bash
# Apply Superkey plist settings (excluding license token and window frames)
# Run via chezmoi on change — auto-generated by capture-superkey-settings.sh

HEADER

for key in "${keys[@]}"; do
  val=$(defaults read com.knollsoft.Superkey "$key" 2>/dev/null || true)
  if [ -z "$val" ]; then
    echo "⚠  Skipping $key (not found in defaults)"
    continue
  fi
  if [[ "$val" =~ ^-?[0-9]+$ ]]; then
    echo "defaults write com.knollsoft.Superkey $key -int $val" >> "$target"
  else
    echo "defaults write com.knollsoft.Superkey $key -string '$val'" >> "$target"
  fi
done

chmod +x "$target"
echo "✓ Regenerated $target"